#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 20 10:33:36 2021

@author: hernan
This script generates accession list tables from the summary files generated by db_survey
"""

#%% libraries
from glob import glob
from datetime import datetime
import pandas as pd
#%% variables
summary_dir = '/home/hernan/PROYECTOS/Graboid/Databases/22_9_2021-11_54_51/Summaries'
#%% functions
# file managing
def list_summ_files(summ_dir):
    # generate list of summary files (*summ) present in the given directory
    summ_files = glob(f'{summ_dir}/*summ')
    return summ_files

def build_summ_tab(summ_files):
    # generate information table for the summary files
    # get taxon, marker, database and path information for each file
    summ_tab = pd.DataFrame(columns = ['Taxon', 'Marker', 'Database', 'File'])
    
    for file in summ_files:
        split_file = file.split('/')[-1].split('.summ')[0].split('_')
        row = {'Taxon':split_file[0],
               'Marker':split_file[1],
               'Database':split_file[2],
               'File':file}
        summ_tab = summ_tab.append(row, ignore_index=True)
    return summ_tab

def generate_filename(taxon, marker):
    filename = f'acc_{taxon}_{marker}.tab'
    return filename

# data loading
def read_BOLD_summ(summ_file):
    # extract a list of accessions from a BOLD summary
    bold_tab = pd.read_csv(summ_file, sep = '\t', encoding = 'latin-1') # latin-1 to parse BOLD files
    accs = bold_tab['sampleid'].tolist()
    return accs

def read_NCBI_summ(summ_file):
    # extract a list of accessions from an NCBI or ENA summary
    ncbi_tab = pd.read_csv(summ_file, sep = '\t')
    accs = ncbi_tab.iloc[:,0].tolist()
    return accs

def read_summ(summ_file, read_func):
    # extract accessions (and generate accessions w/o version number) from summary file
    # read_func specify what function will be used to read the file (read_BOLD_summ or read_NCBI_summ)
    accs = read_func(summ_file)
    
    shortaccs = get_shortaccs(accs)
    acc_series = pd.Series(accs, index = shortaccs, name = 'Accession')
    return acc_series

# data processing
def get_shortaccs(acclist):
    # remove version number from each accession in acclist
    shortaccs = [acc.split('.')[0] for acc in acclist]
    return shortaccs

def make_acc_subtab(acc_series, dbase, tax, mark = ''):
    # add taxon, marker and database information to the accession series
    acc_subtab = acc_series.to_frame()
    acc_subtab['Database'] = dbase
    acc_subtab['Taxon'] = tax
    acc_subtab['Marker'] = mark
    
    return acc_subtab

def make_dbase_series(tab, dbase):
    # generate accession series for the given dbase
    # tab is a subtab generated from grouping the complete summary tab by taxon and marker, should contain a single entry per database
    
    # select the read_func to use
    if dbase == 'BOLD':
        read_func = read_BOLD_summ
    else:
        read_func = read_NCBI_summ
    
    # select the summary file and generate accsession series for it
    summ_file = tab.loc[tab['Database'] == dbase, 'File'].values[0]
    acc_series = read_summ(summ_file, read_func)
    return acc_series

def merge_subtabs(subtabs):
    # merge the given subtabs into one, mind repeated entries
    # order in which subtabs are presented determines priority for repeated entries. When an entry is repeated between two subtabs, the first one to appear is kept
    # list should start with NCBI
    acc_tab = pd.DataFrame(columns = ['Accession', 'Database', 'Taxon', 'Marker'])
    
    for subtab in subtabs:
        acc_idx = set(acc_tab.index)
        st_idx = set(subtab.index)
        
        # only add entries not already present in acc_tab
        diff = st_idx.difference(acc_idx)
        to_add = subtab.loc[diff]
        
        acc_tab = acc_tab.append(to_add)
    return acc_tab

def make_acc_tab(summ_tab, tax, mark):
    # generate a full accession table for the given tax/mark combo
    subtabs = []
    for dbase in ['NCBI', 'BOLD', 'ENA']:
        # generate subtab for each database (if present)
        if dbase in summ_tab['Database'].values:
            dbase_series = make_dbase_series(summ_tab, dbase)
            subtabs.append(make_acc_subtab(dbase_series, dbase, tax, mark))
    merged = merge_subtabs(subtabs)
    return merged

def main(summ_dir, out_dir):
    # Main function, run to generate accession list files
    # TODO, compare with previous databases, check version changes
    summ_tab = build_summ_tab(list_summ_files(summ_dir))
    
    for tax_group in summ_tab.groupby('Taxon'):
        tax = tax_group[0]
        for mark_group in tax_group[1].groupby('Marker'):
            mark = mark_group[0]
            subtab = mark_group[1]
            acc_tab = make_acc_tab(subtab, tax, mark)
            outfile = generate_filename(tax, mark)
            acc_tab.to_csv(f'{out_dir}/{outfile}')
    
#%%