#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 20 10:33:36 2021

@author: hernan
This script generates accession list tables from the summary files generated by db_survey
"""

#%% libraries
from glob import glob
from datetime import datetime
import pandas as pd
#%% variables
summary_dir = '/home/hernan/PROYECTOS/Graboid/Databases/22_9_2021-11_54_51/Summaries'
#%% functions
# file managing
def list_summ_files(summ_dir):
    summ_files = glob(f'{summ_dir}/*summ')
    return summ_files

def build_summ_tab(summ_files):
    # get taxon, marker, database and path information for each file
    summ_tab = pd.DataFrame(columns = ['Taxon', 'Marker', 'Database', 'File'])
    
    for file in summ_files:
        split_file = file.split('/')[-1].split('.summ')[0].split('_')
        row = {'Taxon':split_file[0],
               'Marker':split_file[1],
               'Database':split_file[2],
               'File':file}
        summ_tab = summ_tab.append(row, ignore_index=True)
    return summ_tab

# data loading
def read_BOLD_summ(summ_file):
    bold_tab = pd.read_csv(summ_file, sep = '\t', encoding = 'latin-1') # latin-1 to parse BOLD files
    accs = bold_tab['sampleid'].tolist()
    return accs

def read_NCBI_summ(summ_file):
    ncbi_tab = pd.read_csv(summ_file, sep = '\t')
    accs = ncbi_tab.iloc[:,0].tolist()
    return accs

def read_summ(summ_file, read_func):
    accs = read_func(summ_file)
    
    shortaccs = get_shortaccs(accs)
    acc_series = pd.Series(accs, index = shortaccs, name = 'Accession')
    return acc_series

# data processing
def get_shortaccs(acclist):
    shortaccs = [acc.split('.')[0] for acc in acclist]
    return shortaccs

def make_acc_subtab(acc_series, dbase, tax, mark = ''):
    acc_subtab = acc_series.to_frame()
    acc_subtab['Database'] = dbase
    acc_subtab['Taxon'] = tax
    acc_subtab['Marker'] = mark
    
    return acc_subtab

def make_dbase_series(tab, dbase):
    if dbase == 'BOLD':
        read_func = read_BOLD_summ
    else:
        read_func = read_NCBI_summ
    summ_file = tab.loc[tab['Database'] == dbase, 'File'].values[0]
    acc_series = read_summ(summ_file, read_func)
    return acc_series

def merge_subtabs(subtabs):
    acc_tab = pd.DataFrame(columns = ['Accession', 'Database', 'Taxon', 'Marker'])
    
    for subtab in subtabs:
        acc_idx = set(acc_tab.index)
        st_idx = set(subtab.index)
        diff = st_idx.difference(acc_idx)
        to_add = subtab.loc[diff]
        
        acc_tab = acc_tab.append(to_add)
    return acc_tab

def make_acc_tab(summ_tab, tax, mark):
    subtabs = []
    for dbase in ['NCBI', 'BOLD', 'ENA']:
        if dbase in summ_tab['Database'].values:
            dbase_series = make_dbase_series(summ_tab, dbase)
            subtabs.append(make_acc_subtab(dbase_series, dbase, tax, mark))
    merged = merge_subtabs(subtabs)
    # TODO SAVE acc_table
    return merged

def main(summ_dir):
    summ_tab = build_summ_tab(list_summ_files(summ_dir))
    
    for tax_group in summ_tab.groupby('Taxon'):
        tax = tax_group[0]
        for mark_group in tax_group[1].groupby('Marker'):
            mark = mark_group[0]
            subtab = mark_group[1]
            return make_acc_tab(subtab, tax, mark)
    
#%%
def make_acc_tab(summ_tab):
    acc_tab = pd.DataFrame(columns = ['Taxon', 'Marker', 'Database', 'Accession']) # will store accession numbers

    taxons = summ_tab['Taxon'].unique().tolist()
    for taxon in taxons:
        sub_tab1 = summ_tab.loc[summ_tab['Taxon'] == taxon]
    
        markers = sub_tab1['Marker'].unique().tolist()
        for marker in markers:
            sub_tab2 = sub_tab1.loc[sub_tab1['Marker'] == marker]
            
            sub_acc_tab = pd.DataFrame(columns = ['Taxon', 'Marker', 'Database', 'Accession'])
            db_accs = []
            dbases = sub_tab2['Database'].unique().tolist()
            for dbase in dbases:
                file = sub_tab2.loc[sub_tab2['Database'] == dbase, 'File'].values[0]
                # db_accs[dbase] = read_summ(file, dbase)
                db_accs.append(read_summ(file, dbase))
            
            db_tab = pd.concat(db_accs, axis = 1)
            for db in ['NCBI', 'ENA', 'BOLD']:
                if db in db_tab.columns:
                    col = db_tab[db].dropna()
                    idx = set(col).difference(set(sub_acc_tab))
            return db_tab

    # for taxon in taxons:
    #     tax_tab = pd.DataFrame(columns = ['Taxon', 'Marker', 'Database', 'Accession']) # sub table containing entries for the given taxon, will be incorporated to acc_tab 
    #     for marker in markers:
    #         # TODO handle missing databases
    #         # retrieve summary files
    #         ena_file = summ_tab.loc[(summ_tab['Taxon'] == taxon) & (summ_tab['Marker'] == marker) & (summ_tab['Database'] == 'ENA'), 'File'].values[0]
    #         ncbi_file = summ_tab.loc[(summ_tab['Taxon'] == taxon) & (summ_tab['Marker'] == marker) & (summ_tab['Database'] == 'NCBI'), 'File'].values[0]
    
    #         # read ENA
    #         ena_tab = pd.read_csv(ena_file, sep ='\t')
    #         ena_accs = set(ena_tab['accession'])
    #         # read NCBI
    #         with open(ncbi_file, 'r') as handle:
    #             acc_list = handle.read().splitlines()
    #             ncbi_accs = set([acc.split('.')[0] for acc in acc_list])
            
    #         ncbi_tab = pd.DataFrame({'Taxon':taxon, 'Marker':marker, 'Database':'NCBI', 'Accession':list(ncbi_accs)})
    #         ena_tab = pd.DataFrame({'Taxon':taxon, 'Marker':marker, 'Database':'ENA', 'Accession':list(ena_accs.difference(ncbi_accs))})
            
    #         tax_tab = pd.concat([tax_tab, ncbi_tab, ena_tab])
    #     # read BOLD
        # bold_file = summ_tab.loc[(summ_tab['Taxon'] == taxon) & (summ_tab['Database'] == 'BOLD'), 'File'].values[0]
        # bold_tab = pd.read_csv(bold_file, sep = '\t',encoding = 'latin-1') # latin-1 to parse BOLD files
        # bold_accs = set(bold_tab['sampleid'])
        # core_accs = set(tax_tab.loc[tax_tab['Marker'] == 'COI', 'Accession'])
        # bold_tab = pd.DataFrame({'Taxon':taxon, 'Marker':'COI', 'Database':'BOLD', 'Accession':list(bold_accs.difference(core_accs))})
        # tax_tab = pd.concat([tax_tab, bold_tab])
    
    #     acc_tab = pd.concat([acc_tab, tax_tab])

#%% save results
out_dir = '/home/hernan/PROYECTOS/Graboid/Databases/Acc_lists'
t = datetime.now()
outfile = f'{out_dir}/accessions_{t.day}-{t.month}-{t.year}_{t.hour}-{t.minute}-{t.second}.csv'
acc_tab.to_csv(outfile)